/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Analytics } from './Analytics.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AnalyticsService } from './Analytics.service';
import { AnalyticsController } from './Analytics.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Analytics])],
  providers: [AnalyticsService],
  exports: [AnalyticsService],
  controllers: [AnalyticsController],
})
export class AnalyticsModule {}
