/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Analytics, AnalyticsCreate } from './dtos/Analytics.dto';
import { AnalyticsController } from './Analytics.controller';
import { AnalyticsService } from './Analytics.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('AnalyticsController', () => {
  let controller: AnalyticsController;
  let spyService: AnalyticsService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: AnalyticsService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [AnalyticsController],
      providers: [AnalyticsService, ApiServiceProvider],
    }).compile();

    controller = module.get<AnalyticsController>(AnalyticsController);
    spyService = module.get<AnalyticsService>(AnalyticsService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call AnalyticsController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call AnalyticsController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Analytics();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
