/**
 * This file generated by Apso.
 */
import { SurveyModule } from './Survey/Survey.module';
import { QuestionModule } from './Question/Question.module';
import { ResponseModule } from './Response/Response.module';
import { AnalyticsModule } from './Analytics/Analytics.module';

export default [SurveyModule, QuestionModule, ResponseModule, AnalyticsModule];
