/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Response } from './Response.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ResponseService } from './Response.service';
import { ResponseController } from './Response.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Response])],
  providers: [ResponseService],
  exports: [ResponseService],
  controllers: [ResponseController],
})
export class ResponseModule {}
