/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Response, ResponseCreate } from './dtos/Response.dto';
import { ResponseController } from './Response.controller';
import { ResponseService } from './Response.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('ResponseController', () => {
  let controller: ResponseController;
  let spyService: ResponseService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: ResponseService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [ResponseController],
      providers: [ResponseService, ApiServiceProvider],
    }).compile();

    controller = module.get<ResponseController>(ResponseController);
    spyService = module.get<ResponseService>(ResponseService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call ResponseController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call ResponseController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Response();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
