/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Survey } from './Survey.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { SurveyService } from './Survey.service';
import { SurveyController } from './Survey.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Survey])],
  providers: [SurveyService],
  exports: [SurveyService],
  controllers: [SurveyController],
})
export class SurveyModule {}
