/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Question } from './Question.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { QuestionService } from './Question.service';
import { QuestionController } from './Question.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Question])],
  providers: [QuestionService],
  exports: [QuestionService],
  controllers: [QuestionController],
})
export class QuestionModule {}
