import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class SurveyCreate {
  @ApiProperty()
  title: string;
}

export class Survey {
  @ApiProperty()
  id: number;
  @ApiProperty()
  title: string;
}
