import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class QuestionCreate {
  @ApiProperty()
  text: string;
}

export class Question {
  @ApiProperty()
  id: number;
  @ApiProperty()
  text: string;
}
